//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка по использованию программы &quot;Экзаменатор&quot;.
        ///
        ///МИНИМАЛЬНЫЕ СИСТЕМНЫЕ ТРЕБОВАНИЯ:
        ///---------------------------------------------------------
        ///- Операционная система Microsoft® Windows® XP SP3 (Windows Vista и Windows 7 официально не поддерживаются!)
        ///- Программная платформа Microsoft .NET Framework 4.0
        ///- Процессор Pentium III 1000 МГц или аналогичный Athlon XP
        ///- 256 МБ оперативной памяти
        ///- 1МБ свободного места на жестком диске.
        ///
        ///ДЛЯ РАБОТЫ ПРОГРАММЫ
        ///----------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InfoPicture {
            get {
                object obj = ResourceManager.GetObject("InfoPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа &quot;Экзаменатор&quot; является условно бесплатной.  Данное ПО распространяется автором на взаимно выгодных условиях. Используя программой вы полностью подтверждаете свое согласие с этим лицензионным соглашением и всеми правилами, приведенными ниже.
        ///
        ///ЛИЦЕНЗИОННОЕ СОГЛАШЕНИЕ ПРОГРАММЫ &quot;ЭКЗАМЕНАТОР&quot;
        ///-----------------------------------------------------------------------------------------------------------
        ///1) Пользователь данной программы не имеет права ПРОДАВАТЬ её 3им лицам!
        ///2) Пользователь не имеет пр [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я, Рудаков Дмитрий, автор этой программы, выражаю свою благодарность всем, кто помогал мне при её создании! 
        ///Особо подчеркиваю помощь моих друзей sniper_lunev, /Добрейший-человек/, Iriney и Vitall.
        ///
        ///Также благодарю за помощь: Celly, Петррр, MDmitry_, d3nver, kazrulit, RainS, viktorrrr, pincet..
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
    }
}
